// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB92P0U1qrBCoAObildOJ0O1RoTjGw0L4Y',
    appId: '1:373432566361:web:8fa6461e3f3100a5ebe748',
    messagingSenderId: '373432566361',
    projectId: 'aift-370f8',
    authDomain: 'aift-370f8.firebaseapp.com',
    storageBucket: 'aift-370f8.appspot.com',
    measurementId: 'G-6ZRFTEH3PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLUkl0kS4-pwnbwyT40CKPkJc4zUSOUrY',
    appId: '1:373432566361:android:d22378a6fdf59c59ebe748',
    messagingSenderId: '373432566361',
    projectId: 'aift-370f8',
    storageBucket: 'aift-370f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgnahP0k2LM4JF2K-StIcVVG_uscRbnzc',
    appId: '1:373432566361:ios:52e73d000d08c0eaebe748',
    messagingSenderId: '373432566361',
    projectId: 'aift-370f8',
    storageBucket: 'aift-370f8.appspot.com',
    iosBundleId: 'com.example.aiFitnessTrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgnahP0k2LM4JF2K-StIcVVG_uscRbnzc',
    appId: '1:373432566361:ios:52e73d000d08c0eaebe748',
    messagingSenderId: '373432566361',
    projectId: 'aift-370f8',
    storageBucket: 'aift-370f8.appspot.com',
    iosBundleId: 'com.example.aiFitnessTrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB92P0U1qrBCoAObildOJ0O1RoTjGw0L4Y',
    appId: '1:373432566361:web:6dc0aff6cbdad4e8ebe748',
    messagingSenderId: '373432566361',
    projectId: 'aift-370f8',
    authDomain: 'aift-370f8.firebaseapp.com',
    storageBucket: 'aift-370f8.appspot.com',
    measurementId: 'G-FM5BDFHLXT',
  );

}